---
title: "Single-cell atlas reveals correlates of high cognitive function, dementia, and resilience to Alzheimer's disease pathology"
subtitle: '[Mathys, et al. Cell (2023)](https://doi.org/10.1016/j.cell.2023.08.039)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
    toc: true
    smart: false
vignette: >
  %\VignetteIndexEntry{Single-cell atlas reveals correlates of high cognitive function, dementia, and resilience to Alzheimers disease pathology}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---





<!--- 

cd /sc/arion/projects/CommonMind/hoffman/crumblr_analysis/Mathys_2023
R

system("git pull"); rmarkdown::render("Mathys_2023.Rmd");


# https://hoffmg01.u.hpc.mssm.edu/crumblr_analysis/Mathys_2023/Mathys_2023.html


--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

# Load packages
```{r load.packages, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(DelayedArray)
library(dreamlet)
library(variancePartition)
library(knitr)
library(kableExtra)
library(cowplot)
library(ggplot2)
library(crumblr)
library(ggtree)
library(aplot)
```

# Load data
```{r load.data}
# read H5AD file
file = "/sc/arion/projects/CommonMind/leed62/ref/published/2023_Mathys_Cell_snRNA/cell_browser/ad-aging-brain/240321_2023_Mathys_Cell_snRNA_cb_final_only_counts.h5ad"
sce = readH5AD(file, use_hdf5=TRUE, verbose=TRUE)
counts(sce) = assay(sce, "X")

sce$Cell_Type = factor(sce$Cell_Type, sort(levels(sce$Cell_Type)))

# create pseudobulk 
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "Cell_Type",  
    sample_id = "individualID")

types = c("nonAD", "AD" )
pb$ADdiag2types = factor(pb$ADdiag2types, types)

types = c("nonAD", "earlyAD", "lateAD" )
pb$ADdiag3types = factor(pb$ADdiag3types, types)

pb$CERAD = 5 - pb$ceradsc
```

# UMAP embedding
```{r embedding}
plotProjection(sce, "X_umap", annotation='Major_Cell_Type') 
plotProjection(sce, "X_umap", annotation='Cell_Type')  
```



## Properties of dataset
```{r properties}
df = data.frame(table(pb$ADdiag2types))
colnames(df) = c("Disease status", "Count")

df %>%
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 


df = data.frame(table(pb$ADdiag3types))
colnames(df) = c("Disease status", "Count")

df %>%
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 

df = list()
df$`# Samples` = ncol(pb)
df$`# Subjects` = nlevels(sce$Individual)
df$`# Cells` = ncol(sce)
df = unlist(df)
df = data.frame(Propert=names(df), count = df)

df %>%  
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 
```

# Cell_Type
```{r CT, fig.height=15, fig.width=15}
# Controls only
idx = which(pb$ADdiag2types != "AD")
cobj = crumblr(cellCounts(pb)[idx,])

form = ~ age + sex + Study + pmi 

vp.c = fitExtractVarPartModel(cobj, form, colData(pb)[idx,])
fig.vp = plotPercentBars( vp.c) 

fit = dream(cobj, form, colData(pb)[idx,])
fit = eBayes(fit)

tab = topTable(fit, coef="age", number=Inf)

hc = buildClusterTreeFromPB(pb)

res = treeTest( fit, cobj, hc, coef="age", method="FE")

fig1 = plotTreeTestBeta(res) + xlim(0, 25)

tab$celltype = factor(rownames(tab), rev(get_taxa_name(fig1)))
tab$se = with(tab, logFC/t)

fig2 = ggplot(tab, aes(celltype, logFC)) + 
  geom_hline(yintercept=0, linetype="dashed", color="grey", size=1) +
  geom_errorbar(aes(ymin = logFC - 1.96*se, ymax = logFC + 1.96*se), width=0) +
  geom_point(color="dodgerblue") +
  theme_classic() +
  coord_flip() +
  xlab('') + 
  ylab("Effect size") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

# combine plots
fig2 %>% insert_left(fig1) %>% insert_right(fig.vp)
```

# Combine SST
```{r SST}
df_count = as.data.frame(cellCounts(pb))

i =  grep("SST", colnames(df_count))
df_count[['IN_SST']] = rowSums(df_count[,i])
df_count = df_count[,-i]

cobj = crumblr(df_count[idx,])

form = ~ age + sex + Study + pmi 
fit = dream(cobj, form, colData(pb)[idx,])
fit = eBayes(fit)

tab = topTable(fit, coef="age", number=Inf)
tab

tab[grepl("SST", rownames(tab)),]

df = data.frame(CLR = cobj$E["IN_SST",], 
        se = sqrt(1/cobj$weights["IN_SST",]), 
        fractions = df_count[idx,"IN_SST"] / rowSums(df_count[idx,]), colData(pb)[idx,])

fig1 = ggplot(df, aes(age, fractions)) +
  geom_point() +
  geom_smooth(method="lm") +
  theme_classic() +
  theme(aspect.ratio=1)

fig2 = ggplot(df, aes(age, CLR)) +
  geom_errorbar(aes(ymin=CLR - 1.96*se, ymax=CLR + 1.96*se), width=0, color="grey80") +
  geom_point() +
  geom_smooth(method="lm") +
  coord_fixed(ylim=c(-2, 2.5)) +
  theme_classic() +
  theme(aspect.ratio=1)

cowplot::plot_grid(fig1, fig2)
```











# Session Info
<details>
```{r sessioninfo, cache=FALSE}
sessionInfo()
```
</details>

