---
title: "Human prostate cancer bone metastases have an actionable immunosuppressive microenvironment (GSE143791)"
subtitle: '[Kfoury, et al. Cancer Cell (2021)](https://doi.org/10.1016/j.ccell.2021.09.005)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
    toc: true
    smart: false
vignette: >
  %\VignetteIndexEntry{Human prostate cancer bone metastases have an actionable immunosuppressive microenvironment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

# Load packages
```{r load.packages, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(dreamlet)
library(kableExtra)
library(scattermore)
library(cowplot)
library(ggplot2)
library(tidyverse)
library(ggcorrplot)
library(DelayedArray)

# set block size for reading DelayedMatrix in H5AD file
# The default of 1e8 to small and increasing to the block size 
# (i.e. cache size) to 1e9 decrease run time 
# with increased memory usage
setAutoBlockSize(1e9)
```

# Load data
```{r load.data}
# read H5AD file
file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/Kfoury_CancerCell_2021/Kfoury_CancerCell_2021.h5ad"
sce = readH5AD(file, use_hdf5=TRUE)   

sce$cells = factor(sce$cells, sort(levels(sce$cells)))

# create pseudobulk 
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "cells",  
    sample_id = "ID")
```

# UMAP embedding
```{r embeding}
colData(sce) %>%
  data.frame() %>%
  ggplot(aes(Coord1, Coord2, color=cells)) + 
  geom_scattermore() +
  theme_classic() + 
  theme(aspect.ratio=1, axis.text=element_blank()) +
  scale_color_discrete(name="Cell type")
```


## Properties of dataset
```{r properties}
df = data.frame(table(pb$Status))
colnames(df) = c("Disease status", "Count")

df %>%
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 

df = list()
df$`# Samples` = ncol(pb)
df$`# Subjects` = nlevels(sce$subject.id)
df$`# Cells` = ncol(sce)
df = unlist(df)
df = data.frame(Propert=names(df), count = df)

df %>%  
  kbl(row.names=FALSE) %>% 
  kable_classic(full_width = FALSE) 
```


```{r cca}
form = ~ subject.id + Status + subject.status 
C = canCorPairs(form, colData(pb) )
ggcorrplot(C, hc.order = TRUE)
```


## Plots of cell fractions
```{r fractions, fig.width=9}
fracs = cellCounts(pb) / rowSums(cellCounts(pb))

figList = lapply(levels(pb$Status), function(lvl){
  i = pb$Status == lvl
  plotPercentBars(fracs[i,], col=ggColorHue(ncol(fracs))) + 
    ylab("Cell fractions") + 
    theme(legend.position = "none", axis.text.y=element_blank()) +
    ggtitle(lvl)
})

plot_grid(plotlist = figList)
```

```{r plot.fracs, fig.width=8, fig.height=9}
df = data.frame(fracs, diagnosis = pb$Status, check.names=FALSE)
df = reshape2::melt(df, id.vars="diagnosis")
 
ggplot(df, aes(diagnosis, value, fill=variable)) + 
  geom_violin() +
  geom_boxplot(fill="grey50", width=.1) + 
  facet_wrap(~ variable) +
  theme_classic() +
  theme(aspect.ratio=1, legend.position="none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab(bquote(Fraction~(log[10]))) +
  scale_y_log10() 
```

```{r fraction.table}
df %>%
  group_by(variable, diagnosis) %>%
  mutate(diagnosis = recode(diagnosis, '0' = "Control", '1' = "Alzheimer's"))  %>% 
  summarize(mean = mean(value)) %>%
  pivot_wider(names_from=c('diagnosis'), values_from=c("mean")) %>%
  kbl %>%
  kable_styling(full_width = F)
```



```{r exit, cache=FALSE}
knitr::knit_exit()
```



## crumblr
### Variance partitioning analysis
```{r crumblr}
cobj = crumblr(cellCounts(pb))

form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age) + (1|AD) + pH + PMI

vp.c = fitExtractVarPartModel(cobj, form, colData(pb))

plotVarPart(sortCols(vp.c), label.angle=60, ncol=4) + theme(aspect.ratio=1)
```

```{r plotPercentBars}
fig.vp = plotPercentBars( sortCols(vp.c) )

# analysis with dream()
form = ~ (1|SubID) + (1|poolID) + (1|Sex) + scale(Age) + AD + pH + PMI
fit = dream( cobj, form, colData(pb))
fit = eBayes(fit)
```



### Multivariate test along hierarchy
```{r sd, fig.width=10, fig.height=5}
hc = buildClusterTreeFromPB(pb)

res = treeTest( fit, cobj, hc, coef="AD1")

fig1 = plotTreeTest(res) + xlim(0, 15) + theme(legend.position="none")

tab = topTable(fit, coef="AD1", number=Inf)

tab$celltype = factor(rownames(tab), rev(get_taxa_name(fig1)))
tab$se = with(tab, logFC/t)

fig2 = ggplot(tab, aes(celltype, logFC)) + 
  geom_hline(yintercept=0, linetype="dashed", color="grey", size=1) +
  geom_errorbar(aes(ymin = logFC - 1.96*se, ymax = logFC + 1.96*se), width=0) +
  geom_point(color="dodgerblue") +
  theme_classic() +
  coord_flip() +
  xlab('') + 
  ylab("Effect size") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

# combine plots
fig2 %>% insert_left(fig1) %>% insert_right(fig.vp)
```


### Correlation between coefficient estimates
```{r ggcorrplot}
# get covariance matrix
V = vcov(fit, cobj, coef="AD1")

# convert to correlation matrix
V = cov2cor(V)

# shorten names
rownames(V) = gsub(":AD1", '', rownames(V))
colnames(V) = gsub(":AD1", '', colnames(V))

# sort to match tree
i = match(rev(get_taxa_name(fig1)), rownames(V))

ggcorrplot(V[i,i], outline.color=NA, colors=c("blue3", "white", "red3"))
```





