---
title: "OneK1K single cell RNA-seq"
subtitle: 'https://onek1k.org'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
    self_contained: true
---

<!---


cd /sc/arion/projects/CommonMind/hoffman/crumblr_analysis/Yazar_Science_2022/
R --vanilla

system("git pull"); rmarkdown::render("yazar_2022.Rmd");


# https://hoffmg01.hpc.mssm.edu/crumblr_analysis/Yazar_Science_2022/yazar_2022.html



# cd 

--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = TRUE,
  cache.lazy = FALSE)
```


```{r load, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(dreamlet)
library(crumblr)
library(aplot) 
library(tidyverse) 
library(RColorBrewer)
library(scales)
library(ggtree) 
library(kableExtra)
library(tidyverse) 
library(cowplot)
```

```{r read.data}
# read single cell RNA-seq
file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/Yazar_Science_2022/08984b3c-3189-4732-be22-62f1fe8f15a4.h5ad"
sce = readH5AD(file, use_hdf5=TRUE)
counts(sce) = assay(sce, "X")

# keep cell types with suficient counts
tab = table(sce$cell_type) > 1000
keep = names(tab)[tab]

# Compute pseudobulk by donor
pb <- aggregateToPseudoBulk(sce[,sce$cell_type %in% keep],
    assay = "counts",     
    cluster_id = "cell_type",  
    sample_id = "donor_id",
    verbose = FALSE)

# Compute pseudobulk by pool
pb_pool <- aggregateToPseudoBulk(sce[,sce$cell_type %in% keep],
    assay = "counts",     
    cluster_id = "cell_type",  
    sample_id = "pool_number",
    verbose = FALSE)

rm(sce)

# crumblr transform
cobj = crumblr(cellCounts(pb)[,keep])
```

# Bar plots of cell composition
```{r barplot, fig.width=18, fig.height=6}
# By donor
df = cellCounts(pb)[,keep] %>%
        data.frame
df_fracs = df / rowSums(df) 

df_fracs %>%
  rowid_to_column("Sample") %>% 
  pivot_longer(!Sample) %>%
  ggplot(aes(Sample, value, fill=name)) +
    geom_bar(stat="identity") +
    theme(legend.position="none", aspect.ratio=1/4) +
    coord_cartesian(expand=FALSE) +
    ylab("Cell fraction")

# By pool
df = cellCounts(pb_pool)[,keep] %>%
        data.frame
df_fracs = df / rowSums(df) 

df_fracs %>%
  rowid_to_column("Pool") %>% 
  pivot_longer(!Pool) %>%
  ggplot(aes(Pool, value, fill=name)) +
    geom_bar(stat="identity") +
    theme(legend.position="none", aspect.ratio=1/4) +
    coord_cartesian(expand=FALSE) +
    ylab("Cell fraction")
```



```{r analysis}
form = ~ age + (1|sex) + (1|pool_number) 
res.vp = fitExtractVarPartModel(cobj, form, colData(pb) )

cols = c(brewer.pal(ncol(res.vp)-1, "Set1"), "grey85")
fig.vp = plotPercentBars(sortCols(res.vp), col=cols)

form = ~ age + (1|sex) + (1|pool_number) 
fit = dream(cobj, form, colData(pb))
fit = eBayes(fit)
 
hc = buildClusterTreeFromPB(pb)
```

```{r topTable}
topTable(fit, coef="age", number=Inf) %>%   
  select(logFC, AveExpr, t, P.Value, adj.P.Val) %>% 
  kbl() %>%  
  kable_classic(full_width = FALSE)
```


```{r treeTest}
res = treeTest( fit, cobj, hc, coef="age")
```

```{r plots, fig.width=14, fig.height=5.5}
fig1 = plotTreeTestBeta(res) + ggtitle('Age') 

fig2 = crumblr::plotForest(res, hide=TRUE)

# combine plots
fig2 %>% insert_left(fig1) %>% insert_right(fig.vp) 
```

# Plot each regression
```{r plot.regressions.CLR, fig.height=18, fig.width=10}
library(ggrepel)
# compute residuals
form = ~ (1|sex) + (1|pool_number) 
fit = dream(cobj, form, colData(pb))

# plot of CLR
figList = lapply(rownames(cobj$E), function(CT){

  df = data.frame(CLR = cobj$E[CT,],
                  se = 1/sqrt(cobj$weights[CT,]),
                  colData(pb),
                  counts = cellCounts(pb)[,CT],
                  totalCells = rowSums(cellCounts(pb)))

  # points to highlight
  df_count1 = df %>%
    # filter(counts < 2) %>%
    arrange(-se) %>% 
    head(2) 

  df_count2 = df %>%
    arrange(se, -counts) %>% 
    head(2) 

  df_count = rbind(df_count1, df_count2)

  df %>% 
    ggplot(aes(age, CLR, color=se, weight=1/se^2)) +
      geom_point() +
      theme(aspect.ratio=1) +
      theme_classic() +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1) +
      ggtitle(gsub(",", "\n", CT)) +
      scale_color_gradient(low=muted('red', 70, 10), high="red", name = "SE") +
      geom_smooth(method=lm, formula = y ~ x, color="navy", se=FALSE) +
      geom_text_repel(data=df_count, aes(age, CLR, label=paste(counts, totalCells, sep=' / ')), color="black", box.padding=2) 
})

plot_grid(plotlist=figList, ncol=3)
```

```{r nonlinear}
library(splines)
i = 10
figList[[i]] + 
  geom_smooth(method=lm, formula = y ~ x + I(x^2), color="green", se=FALSE) +
  geom_smooth(method="lm", formula = y ~ x + I(x^2), weight=1, color="turquoise", se=FALSE) 
```



```{r all.nonlinear, fig.height=18, fig.width=10}
figList2 = lapply( figList, function(fig){
  fig + 
  geom_smooth(method=lm, formula = y ~ x + I(x^2), color="green", se=FALSE) +
  geom_smooth(method="lm", formula = y ~ x + I(x^2), weight=1, color="turquoise", se=FALSE)
  })

plot_grid(plotlist=figList2, ncol=3)
```



```{r plot.regressions.residuals, fig.height=18, fig.width=10}
# plot of residuals
figList = lapply(rownames(cobj$E), function(CT){

  df = data.frame(residuals = residuals(fit)[CT,],
                  se = 1/sqrt(cobj$weights[CT,]),
                  colData(pb))

  df %>% 
    ggplot(aes(age, residuals, color=se, weight=1/se^2)) +
      geom_point() +
      theme(aspect.ratio=1) +
      theme_classic() +
      theme(plot.title = element_text(hjust = 0.5), aspect.ratio=1) +
      ggtitle(gsub(",", "\n", CT)) +
      scale_color_gradient(low=muted('red', 80, 1), high="red", name = "SE") +
      geom_smooth(method=lm, formula = y ~ x, color="navy", se=FALSE)
})

plot_grid(plotlist=figList, ncol=3)
```


<!---


# Prediction
```{r prediction}
library(glmnet)

idx.train = colData(pb)$pool_number %in% seq(60)

y = colData(pb)$age
alpha = 0

X1 = t(cobj$E)
fit1 = cv.glmnet(X1[idx.train,], y[idx.train], alpha = alpha)

X2 = t(standardize(cobj))
fit2 = cv.glmnet(X2[idx.train,], y[idx.train], alpha = alpha)

# fractions
X3 = apply(cellCounts(pb)[,keep], 1, function(x) x / sum(x))
X3 = t(X3)
fit3 = cv.glmnet(X3[idx.train,], y[idx.train], alpha = alpha)

pdf("~/www/test.pdf")
plot(fit1)
plot(fit2)
plot(fit3)
dev.off()

ypred1 = predict(fit1, newx = X1[!idx.train,], s = "lambda.1se")
ypred2 = predict(fit2, newx = X2[!idx.train,], s = "lambda.1se")
ypred3 = predict(fit3, newx = X3[!idx.train,], s = "lambda.1se")

cor(y[!idx.train], ypred1)
cor(y[!idx.train], ypred2)
cor(y[!idx.train], ypred3)

```


--->































