---
title: "Analysis of single cell RNA-seq in autism"
subtitle: '[Velmeshev, et al. 2019](https://www.science.org/doi/10.1126/science.aav8130)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---



<!---

cd /sc/arion/projects/CommonMind/hoffman/crumblr_analysis/Velmeshev_2019
ml git
R

system("git pull"); rmarkdown::render("Velmeshev_2019.Rmd")



https://hoffmg01.hpc.mssm.edu/crumblr_analysis/Velmeshev_2019/Velmeshev_2019.html

--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  package.startup.message = FALSE,
  cache.lazy = FALSE)
```

# Load packages
```{r pkgs, cache=FALSE}
library(zellkonverter)
library(SingleCellExperiment)
library(dreamlet)
library(ggplot2)
library(tidyverse)
library(aplot)
library(ggtree)
library(scattermore)
library(crumblr)
library(ggcorrplot)
library(cowplot)
library(BiocParallel)

library(DelayedArray)
setAutoBlockSize(1e9)
```

# Load data
```{r load.data}
# read H5AD files
file = "/sc/arion/projects/CommonMind/hoffman/crumblr_analysis/Velmeshev_2019/data/Velmeshev_2019.h5ad"
sce = readH5AD(file, use_hdf5=TRUE)

sce$diagnosis = factor(sce$diagnosis, c("Control", "ASD"))

pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "cluster",  
    sample_id = "sample", 
    BPPARAM = SnowParam(6, progressbar=TRUE))
```

## tNSE
```{r tsne}
reducedDim(sce, "tSNE") %>%
  as_tibble %>%
  cbind( cluster = sce$cluster) %>% 
  ggplot(aes(tsne1,tsne2, color=cluster)) +
    geom_scattermore() +
    theme_void() +
    theme(aspect.ratio=1)
```
    

```{r cca}
form = ~ individual + region + age + sex + diagnosis + Capbatch + Seqbatch + post.mortem.interval..hours. + RNA.Integrity.Number

C = canCorPairs(form, colData(pb) )
ggcorrplot(C, hc.order = TRUE)
```

# Plots of cell fractions
```{r fractions, fig.width=9}
fracs = cellCounts(pb) / rowSums(cellCounts(pb))

i = pb$diagnosis=="Control"
fig1 = plotPercentBars(fracs[i,], col=ggColorHue(ncol(fracs))) + ylab("Cell fractions") + theme(legend.position = "none")
i = pb$diagnosis=="ASD"
fig2 = plotPercentBars(fracs[i,], col=ggColorHue(ncol(fracs))) + ylab("Cell fractions")

plot_grid(fig1, fig2, rel_widths=c(.8,1))
```

```{r plot.fracs}
df = data.frame(fracs, diagnosis = pb$diagnosis, check.names=FALSE)
df = reshape2::melt(df, id.vars="diagnosis")

ggplot(df, aes(diagnosis, value, fill=variable)) + 
  geom_violin() +
  geom_boxplot(fill="grey50", width=.1) + 
  facet_wrap(~ variable) +
  theme_classic() +
  theme(aspect.ratio=1, legend.position="none") +
  ylab("Fraction")
```





# crumblr
```{r crumblr}
cobj = crumblr(cellCounts(pb))

form = ~ (1|individual) + (1|region) + age + (1|sex) + (1|diagnosis) + (1|Capbatch) + (1|Seqbatch) + post.mortem.interval..hours. + RNA.Integrity.Number

vp.c = fitExtractVarPartModel(cobj, form, colData(pb))

plotVarPart(sortCols(vp.c), label.angle=60, ncol=4) 

fig.vp = plotPercentBars( sortCols(vp.c) )
fig.vp

# analysis with dream()
form = ~ (1|individual) + (1|region) + age + (1|sex) + diagnosis + (1|Capbatch) + (1|Seqbatch) + post.mortem.interval..hours. + RNA.Integrity.Number
fit = dream( cobj, form, colData(pb))
fit = eBayes(fit)
```



## Multivariate test along hierarchy
```{r sd, fig.width=9}
hc = buildClusterTreeFromPB(pb)

res = treeTest( fit, cobj, hc, coef="diagnosisASD")

fig1 = plotTreeTest(res) + xlim(0, 9) + theme(legend.position="none")

tab = topTable(fit, coef="diagnosisASD", number=Inf)

tab$celltype = factor(rownames(tab), rev(get_taxa_name(fig1)))
tab$se = with(tab, logFC/t)

fig2 = ggplot(tab, aes(celltype, logFC)) + 
  geom_hline(yintercept=0, linetype="dashed", color="grey", size=1) +
  geom_errorbar(aes(ymin = logFC - 1.96*se, ymax = logFC + 1.96*se), width=0) +
  geom_point(color="dodgerblue") +
  theme_classic() +
  coord_flip() +
  xlab('') + 
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

# combine plots
fig2 %>% insert_left(fig1) %>% insert_right(fig.vp)
```


## Correlation between coefficient estimates
```{r ggcorrplot}
# get covariance matrix
V = vcov(fit, cobj, coef="diagnosisASD")

# convert to correlation matrix
V = cov2cor(V)

# shorten names
rownames(V) = gsub(":diagnosisASD", '', rownames(V))
colnames(V) = gsub(":diagnosisASD", '', colnames(V))

# sort to match tree
i = match(rev(get_taxa_name(fig1)), rownames(V))

ggcorrplot(V[i,i], outline.color=NA, colors=c("blue3", "white", "red3"))
```




