---
title: "1M-scBloodNL"
subtitle: 'crumblr analysis'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
output: 
  html_document:
    toc: true
    smart: true
params:
  dataset: NULL
  variable_type: NULL
  ctst_key: NULL
---


<!---

cd /sc/arion/projects/CommonMind/hoffman/crumblr_analysis/1M-scBloodNL
ml python git
git pull
R --vanilla


system("git pull"); rmarkdown::render("1M-scBloodNL_crumblr.Rmd");

https://hoffmg01.hpc.mssm.edu/crumblr_analysis/



--->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  package.startup.message = FALSE,
  cache = FALSE,
  cache.lazy = FALSE)
```


```{r load}
suppressPackageStartupMessages({
library(zellkonverter)
library(SingleCellExperiment)
library(aplot)
library(ggtree)
library(dreamlet)
library(crumblr)
library(cowplot)
library(DelayedArray)
})
setAutoBlockSize(1e9)

file = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/1M-scBloodNL/1M_v2_20201029.h5ad"
sce = readH5AD(file, use_hdf5=TRUE)

sce$sample_id = with(colData(sce), paste(assignment, as.character(timepoint), sep='_'))

pb = aggregateToPseudoBulk(sce[1:100,], 
        assay = "counts",    
        cluster_id = 'cell_type', 
        sample_id = 'sample_id',
        verbose=FALSE)


pb$Time = rep("tp0", ncol(pb))
pb$Time[grep("^3", pb$timepoint)] = "tp3"
pb$Time[grep("^24", pb$timepoint)] = "tp24"

pb$Treatment = rep("none", ncol(pb))
pb$Treatment[grep("hCA$", pb$timepoint)] = "hCA"
pb$Treatment[grep("hPA$", pb$timepoint)] = "hPA"
pb$Treatment[grep("hMTB$", pb$timepoint)] = "hMTB"
pb$TreatTime = paste(pb$Treatment, pb$Time, sep="_")

pb$Donor = factor(pb$assignment)

pb = pb[,pb$timepoint !="NA"]
```

```{r crumblr}
cobj = crumblr(cellCounts(pb))

plotCorrMatrix( cor(t(cobj$E)) )

form = ~ (1|Donor) + (1|Treatment) + (1|Time)
vp.c = fitExtractVarPartModel(cobj, form, colData(pb))

plotVarPart(sortCols(vp.c), label.angle=60, ncol=4) 

plotPercentBars( sortCols(vp.c) )

form = ~ 0 + TreatTime + (1|Donor)
contrasts = c(
	hCA_3_vs_0 = "TreatTimehCA_tp3 - TreatTimenone_tp0",
	hMTB_3_vs_0 = "TreatTimehMTB_tp3 - TreatTimenone_tp0",
	hPA_3_vs_0 = "TreatTimehPA_tp3 - TreatTimenone_tp0", 
	hCA_3_vs_24 = "TreatTimehCA_tp24 - TreatTimehCA_tp3",
	hMTB_3_vs_24 = "TreatTimehMTB_tp24 - TreatTimehMTB_tp3",
	hPA_3_vs_24 = "TreatTimehPA_tp24 - TreatTimehPA_tp3")

L = makeContrastsDream(form, colData(pb), contrasts = contrasts)
fit = dream( cobj, form, colData(pb), L=L)
fit = eBayes(fit)

colnames(coef(fit))

hc = buildClusterTreeFromPB(pb)

figList = lapply(names(contrasts), function(ctst){

  res = treeTest( fit, cobj, hc, coef=ctst)

  fig1 = plotTreeTest(res) + xlim(0, 15) + theme(legend.position="none") + ggtitle(ctst)

  tab = topTable(fit, coef=ctst, number=Inf)

  tab$celltype = factor(rownames(tab), rev(get_taxa_name(fig1)))
  tab$se = with(tab, logFC/t)

  fig2 = ggplot(tab, aes(celltype, logFC)) + 
  geom_hline(yintercept=0, linetype="dashed", color="grey", size=1) +
  geom_errorbar(aes(ymin = logFC - 1.96*se, ymax = logFC + 1.96*se), width=0) +
  geom_point(color="dodgerblue") +
  theme_classic() +
  coord_flip() +
  xlab('') + 
  ylab("Effect size") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

  # combine plots
  fig2 %>% insert_left(fig1) 
})
```

```{r plot_grid, fig.height=50}
for(fig in figList){
  print(fig)
}
```







