---
title: "Multimodally profiling memory T cells from a tuberculosis cohort identifies cell state associations with demographics, environment and disease (GSE158769)"
subtitle: '[Nathan, et al. Nat Immunol  (2021)](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE158769)'
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
    toc: true
    smart: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE,
  cache.lazy = FALSE)
```

Perform dreamlet analysis of single cell data assaying T cell populations in donors infected with tuberculosis.

# Loading libraries
```{r load.packages, cache=FALSE}
library(SingleCellExperiment)
library(zellkonverter)
library(ggplot2)
library(scattermore)
library(crumblr)
library(aplot)
library(tidyverse)
library(dreamlet)
library(kableExtra)
library(ggcorrplot)

library(DelayedArray)
setAutoBlockSize(1e9)
```

# Load data
```{r load.data}
# read H5AD file
path = "/sc/arion/projects/CommonMind/hoffman/scRNAseq_data/Nathan_NatImm_2021/"
file = paste0(path, "/Nathan_NatImm_2021.h5ad")
sce = readH5AD(file, use_hdf5=TRUE)   

# get only single-cell RNA-seq
# rest is CITE-seq proteins
only_rna = grep("prot", rownames(sce), invert=TRUE)

# create variable that distinguishes cells from the same donor
# but different batches
sce$donor_batch = with(colData(sce), paste(donor, batch))
sce$batch = factor(sce$batch)
sce$season = factor(sce$season)
sce$TB_status = factor(sce$TB_status, c("CONTROL", "CASE"))

reducedDim(sce, "UMAP") = with(colData(sce), data.frame(UMAP_1, UMAP_2))

# sort cell clusters by name
sce = sce[only_rna,sce$cluster_name != "NA"]
colData(sce) = droplevels(colData(sce))
tab = colData(sce) %>%
  as_tibble %>%
  group_by(cluster_ids, cluster_name) %>%
  filter(row_number()==1) %>%
  summarise(cluster_ids, cluster_name) %>%
  arrange(as.numeric(gsub("C-", '', cluster_ids)))

sce$cluster_name = factor(sce$cluster_name, unique(tab$cluster_name))
sce$cluster_ids = factor(sce$cluster_ids, unique(tab$cluster_ids))
```


## Plot UMAP
```{r UMAP}
colData(sce) %>%  
  data.frame %>%
  ggplot(aes(UMAP_1, UMAP_2, color=cluster_name)) +
    geom_scattermore() +
    theme_classic() +
    theme(aspect.ratio=1)
```

## Create pseudobulk
```{r pb}
pb <- aggregateToPseudoBulk(sce,
    assay = "counts",     
    cluster_id = "cluster_name",  
    sample_id = "donor_batch")
```

# Evaluate crumblr and build tree
```{r test.crumblr}
# run crumblr on cell counts
cobj = crumblr(cellCounts(pb))

# build tree from pseudobulk expression
hcl = buildClusterTreeFromPB( pb )
```


## Variance partitioning analysis
```{r vp}
form = ~ (1|TB_status) + (1|donor) + (1|batch) + (1|season) + (1|sex) + age + I(age^2) + prop_NAT

vp = fitExtractVarPartModel(cobj, form, colData(pb))

plotVarPart(sortCols(vp))
```

## Differential testing
```{r diff.test}
# Run precision-weighted linear mixed model using dream()
# and compute empirical Bayes moderated t-statistics
form = ~ TB_status + (1|donor) + (1|batch) + (1|season) + (1|sex) + age + I(age^2) + prop_NAT
fit = dream(cobj, form, colData(pb))
fit = eBayes(fit) 

# show results
topTable(fit, coef='TB_statusCASE', number=Inf) %>%   
  select(logFC, AveExpr, t, P.Value, adj.P.Val) %>% 
  kbl() %>%  
  kable_classic(full_width = FALSE)
```

## Multivariate test along hierarchy
```{r treeTest, fig.height=5, fig.width=9}
# Perform multivariate testing 
res1 = treeTest( fit, cobj, hcl, coef="TB_statusCASE")

# plot tree with results
fig.tree = plotTreeTest(res1) + xlim(0, 15) 

# plot of logFC
tab = topTable(fit, "TB_statusCASE", number=Inf, sort.by="none")
tab$celltype = factor(rownames(tab), rev(get_taxa_name(fig.tree)))
tab$se = with(df, logFC/ t)

fig.logFC = ggplot(tab, aes(celltype, logFC)) +
  geom_hline(yintercept=0, linetype="dashed", color="grey50") + 
  geom_errorbar(aes(ymin=logFC - 1.96*se, ymax=logFC + 1.96*se), width=0) +
  geom_point(color="dodgerblue") +
  coord_flip() +
  theme_classic() +
  xlab('') +
  theme(aspect.ratio=3, axis.text.y = element_blank())

# combine plots
fig.logFC %>% insert_left(fig.tree)
```



```{r ggcorrplot}
V = vcov(fit, cobj, coef="TB_statusCASE")
V = cov2cor(V)
rownames(V) = gsub(":TB_statusCASE", '', rownames(V))
colnames(V) = gsub(":TB_statusCASE", '', colnames(V))

i = match(rev(get_taxa_name(fig.tree)), rownames(V))

ggcorrplot(V[i,i], outline.color=NA, colors=c("blue3", "white", "red3"), lab_size=2)
```






# Session info
<details>
```{r sessionInfo}
sessionInfo()
```
</details>














